{% set name = "graphql-ws" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56373c4769a31fba6eabb9487caa94f3018ab650c53945c0447ac2693cb6e693

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
    - pytest-runner
  run:
    - python >=2.7
    - graphql-core >=2.0,<3

test:
  imports:
    - graphql_ws

about:
  home: https://github.com/graphql-python/graphql-ws
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: GraphQL websockets

  description: |
    GraphQL websockets. Websocket server for GraphQL subscriptions.
  doc_url: https://github.com/graphql-python/graphql-ws
  dev_url: https://github.com/graphql-python/graphql-ws

extra:
  recipe-maintainers:
    - kinow
    - hjoliver
